### ISSUE TITLE
Copy Objects in old Log Archive to new Landingzone

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/cds-aws-lz#121]
The old Log Archive has about 500GB of data that needs to be transferred over. 

Transfer from account 925306372402

Mainly aws-landing-zone-logs-925306372402-ca-central-1 bucket

https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-batch-replication-batch.html

Need to know cost associated with file transfer.

**Comment by gcharest** [comment]
Transfer account to: 274536870005

**Comment by gcharest** [comment]
Planned work:
- Create new S3 bucket in destination account
- Setup S3 Batch Replication

Planned cost: <$100

**Comment by gcharest** [comment]
Further docs reading:

- Need to have [manifest created](https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops-create-job.html#specify-batchjob-manifest), listing all objects within the bucket. Known options include manually listing objects or using S3 Inventory to generate the manifest. Since there are millions of objects, going to test S3 Inventory
- Hitting a roadblock with applying Allow s3:PutObject policy on the destination bucket for the manifests generation.

**Comment by gcharest** [comment]
Batch job started, currently generating the Manifest (list of all objects to be replicated)


![Image](https://user-images.githubusercontent.com/1690085/196255266-b561f968-ceb0-4d64-80cf-c395c1e5780b.png)

**Comment by gcharest** [comment]
Completed using S3 Batch Replication
